version: '3.8'

services:
  growthness_api:
    container_name: growthness_api
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "yes 'y' | python manage.py makemigrations && yes 'y' | python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - growthness_redis
      - growthness_celery
      - growthness_db

  growthness_celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A growthness worker -l info  
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - growthness_redis

  growthness_redis:
    image: redis:6.2
    container_name: growthness_redis
    ports:
      - "6379:6379"

  growthness_db:
    container_name: growthness_db
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com 
      PGADMIN_DEFAULT_PASSWORD: admin         
    ports:
      - "8090:80"
    depends_on:
      - growthness_db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
