# Generated by Django 4.2.15 on 2024-08-31 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_frequency_habit_frequencies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='daily_goal',
            new_name='goal',
        ),
    ]
