# Generated by Django 4.2.9 on 2024-09-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='height_measure',
            field=models.CharField(default='m', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='weight_measure',
            field=models.CharField(default='kg', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='goals',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_goals', to='authentication.usergoals'),
        ),
    ]
