# Generated by Django 4.2.15 on 2024-09-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complete_profile', '0001_initial'),
        ('authentication', '0004_usergoals_user_height_user_height_measure_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserGoals',
        ),
        migrations.AlterField(
            model_name='user',
            name='goals',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_goals', to='complete_profile.usergoals'),
        ),
    ]
