# Generated by Django 4.2.15 on 2024-09-15 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complete_profile', '0001_initial'),
        ('authentication', '0005_delete_usergoals_alter_user_goals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='goals',
        ),
        migrations.AddField(
            model_name='user',
            name='goals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_goal', to='complete_profile.usergoals'),
        ),
    ]
