# Generated by Django 4.2.15 on 2024-09-15 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_user_goals_user_goals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='goals',
            new_name='goal',
        ),
    ]
