# Generated by Django 4.2.15 on 2024-09-24 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exercise_type', models.CharField(choices=[('gym', 'Gym'), ('cardio', 'Cardio')], max_length=50)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('distance', models.FloatField(blank=True, help_text='Distance in kilometers', null=True)),
                ('average_velocity', models.FloatField(blank=True, help_text='Average velocity in km/h', null=True)),
                ('pace', models.FloatField(blank=True, help_text='Pace in minutes per kilometer', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RoutineExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_goal', models.PositiveIntegerField(blank=True, help_text='Weight goal for this exercise', null=True)),
                ('reps_goal', models.PositiveIntegerField(blank=True, help_text='Reps goal for this exercise', null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.routine')),
            ],
        ),
        migrations.AddField(
            model_name='routine',
            name='exercises',
            field=models.ManyToManyField(through='exercises.RoutineExercise', to='exercises.exercise'),
        ),
        migrations.AddField(
            model_name='routine',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('target_date', models.DateField()),
                ('achieved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_logged', models.DateField()),
                ('weight', models.PositiveIntegerField(blank=True, help_text='Weight used during exercise', null=True)),
                ('reps', models.PositiveIntegerField(blank=True, help_text='Reps completed', null=True)),
                ('distance_logged', models.FloatField(blank=True, help_text='Distance in kilometers logged', null=True)),
                ('average_velocity_logged', models.FloatField(blank=True, help_text='Average velocity in km/h logged', null=True)),
                ('pace_logged', models.FloatField(blank=True, help_text='Pace in minutes per kilometer logged', null=True)),
                ('routine_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.routineexercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
