# Generated by Django 4.2.15 on 2024-11-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_alter_routineexercise_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration in minutes', null=True),
        ),
    ]
