# Generated by Django 4.2.15 on 2024-09-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complete_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergoals',
            name='icon',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
